# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/personal/code/pychmviewer/window_main.ui'
#
# Created: Mon Dec 13 16:08:06 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(873, 591)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pychmviewer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.widget = QtGui.QWidget(MainWindow)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        #self.WebViewsWidget = PyChmTabs(self.widget)
        #self.WebViewsWidget.setObjectName(_fromUtf8("WebViewsWidget"))
        #self.horizontalLayout.addWidget(self.WebViewsWidget)
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Panels = QtGui.QMenu(self.menubar)
        self.menu_Panels.setObjectName(_fromUtf8("menu_Panels"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_Windows = QtGui.QMenu(self.menubar)
        self.menu_Windows.setObjectName(_fromUtf8("menu_Windows"))
        MainWindow.setMenuBar(self.menubar)
        self.mainToolbar = QtGui.QToolBar(MainWindow)
        self.mainToolbar.setOrientation(QtCore.Qt.Horizontal)
        self.mainToolbar.setObjectName(_fromUtf8("mainToolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolbar)
        self.navToolbar = QtGui.QToolBar(MainWindow)
        self.navToolbar.setOrientation(QtCore.Qt.Horizontal)
        self.navToolbar.setObjectName(_fromUtf8("navToolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.navToolbar)
        self.viewToolbar = QtGui.QToolBar(MainWindow)
        self.viewToolbar.setOrientation(QtCore.Qt.Horizontal)
        self.viewToolbar.setObjectName(_fromUtf8("viewToolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.viewToolbar)
        self.mainStatusBar = QtGui.QStatusBar(MainWindow)
        self.mainStatusBar.setObjectName(_fromUtf8("mainStatusBar"))
        MainWindow.setStatusBar(self.mainStatusBar)
        self.dockTopics = QtGui.QDockWidget(MainWindow)
        self.dockTopics.setAcceptDrops(False)
        self.dockTopics.setAccessibleDescription(_fromUtf8(""))
        self.dockTopics.setObjectName(_fromUtf8("dockTopics"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockTopics.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockTopics)
        self.dockIndex = QtGui.QDockWidget(MainWindow)
        self.dockIndex.setObjectName(_fromUtf8("dockIndex"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.dockIndex.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockIndex)
        self.dockSearch = QtGui.QDockWidget(MainWindow)
        self.dockSearch.setObjectName(_fromUtf8("dockSearch"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.dockSearch.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockSearch)
        self.dockBookmark = QtGui.QDockWidget(MainWindow)
        self.dockBookmark.setAccessibleName(_fromUtf8(""))
        self.dockBookmark.setObjectName(_fromUtf8("dockBookmark"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.dockBookmark.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockBookmark)
        self.actionPrintPage = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrintPage.setIcon(icon1)
        self.actionPrintPage.setObjectName(_fromUtf8("actionPrintPage"))
        self.settings_SettingsAction = QtGui.QAction(MainWindow)
        self.settings_SettingsAction.setObjectName(_fromUtf8("settings_SettingsAction"))
        self.bookmark_AddAction = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_add_bookmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bookmark_AddAction.setIcon(icon2)
        self.bookmark_AddAction.setObjectName(_fromUtf8("bookmark_AddAction"))
        self.actionZoomIn = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_font_increase.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon3)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoomOut = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_font_decrease.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon4)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionZoomOff = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_font_norm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOff.setIcon(icon5)
        self.actionZoomOff.setObjectName(_fromUtf8("actionZoomOff"))
        self.actionViewHtmlSource = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_view_source.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewHtmlSource.setIcon(icon6)
        self.actionViewHtmlSource.setObjectName(_fromUtf8("actionViewHtmlSource"))
        self.view_Toggle_fullscreen_action = QtGui.QAction(MainWindow)
        self.view_Toggle_fullscreen_action.setCheckable(True)
        self.view_Toggle_fullscreen_action.setAutoRepeat(False)
        self.view_Toggle_fullscreen_action.setObjectName(_fromUtf8("view_Toggle_fullscreen_action"))
        self.view_Toggle_contents_action = QtGui.QAction(MainWindow)
        self.view_Toggle_contents_action.setCheckable(True)
        self.view_Toggle_contents_action.setChecked(True)
        self.view_Toggle_contents_action.setAutoRepeat(False)
        self.view_Toggle_contents_action.setObjectName(_fromUtf8("view_Toggle_contents_action"))
        self.actionLocate = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_locate_in_content.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLocate.setIcon(icon7)
        self.actionLocate.setObjectName(_fromUtf8("actionLocate"))
        self.actionChangeEncoding = QtGui.QAction(MainWindow)
        self.actionChangeEncoding.setObjectName(_fromUtf8("actionChangeEncoding"))
        self.actionOpenFile = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_open_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFile.setIcon(icon8)
        self.actionOpenFile.setObjectName(_fromUtf8("actionOpenFile"))
        self.nav_actionBack = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_actionBack.setIcon(icon9)
        self.nav_actionBack.setObjectName(_fromUtf8("nav_actionBack"))
        self.nav_actionForward = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_actionForward.setIcon(icon10)
        self.nav_actionForward.setObjectName(_fromUtf8("nav_actionForward"))
        self.nav_actionHome = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icon_home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_actionHome.setIcon(icon11)
        self.nav_actionHome.setObjectName(_fromUtf8("nav_actionHome"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExtractFile = QtGui.QAction(MainWindow)
        self.actionExtractFile.setObjectName(_fromUtf8("actionExtractFile"))
        self.actionQuitApp = QtGui.QAction(MainWindow)
        self.actionQuitApp.setObjectName(_fromUtf8("actionQuitApp"))
        self.actionToggleSidebar = QtGui.QAction(MainWindow)
        self.actionToggleSidebar.setObjectName(_fromUtf8("actionToggleSidebar"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionSelectAll = QtGui.QAction(MainWindow)
        self.actionSelectAll.setObjectName(_fromUtf8("actionSelectAll"))
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName(_fromUtf8("actionFind"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionFindNext = QtGui.QAction(MainWindow)
        self.actionFindNext.setObjectName(_fromUtf8("actionFindNext"))
        self.actionFindPrevious = QtGui.QAction(MainWindow)
        self.actionFindPrevious.setObjectName(_fromUtf8("actionFindPrevious"))
        self.menu_Settings.addAction(self.settings_SettingsAction)
        self.menu_File.addAction(self.actionOpenFile)
        self.menu_File.addAction(self.actionPrintPage)
        self.menu_File.addAction(self.actionExtractFile)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuitApp)
        self.menu_View.addAction(self.actionZoomIn)
        self.menu_View.addAction(self.actionZoomOut)
        self.menu_View.addAction(self.actionZoomOff)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionChangeEncoding)
        self.menu_View.addAction(self.actionViewHtmlSource)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionLocate)
        self.menu_View.addSeparator()
        self.menu_Panels.addAction(self.actionToggleSidebar)
        self.menu_Panels.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menu_Edit.addAction(self.actionCopy)
        self.menu_Edit.addAction(self.actionSelectAll)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionFind)
        self.menu_Edit.addAction(self.actionFindNext)
        self.menu_Edit.addAction(self.actionFindPrevious)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Panels.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Windows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.mainToolbar.addAction(self.actionOpenFile)
        self.mainToolbar.addAction(self.actionPrintPage)
        self.navToolbar.addAction(self.nav_actionHome)
        self.navToolbar.addAction(self.nav_actionBack)
        self.navToolbar.addAction(self.nav_actionForward)
        self.viewToolbar.addAction(self.actionLocate)
        self.viewToolbar.addAction(self.actionZoomIn)
        self.viewToolbar.addAction(self.actionZoomOut)
        self.viewToolbar.addAction(self.actionZoomOff)
        self.viewToolbar.addAction(self.actionViewHtmlSource)
        self.viewToolbar.addAction(self.bookmark_AddAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pychmviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Panels.setTitle(QtGui.QApplication.translate("MainWindow", "&Panels", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Windows.setTitle(QtGui.QApplication.translate("MainWindow", "&Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.mainToolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "general toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.navToolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "navigation toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.viewToolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "action toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockTopics.setStatusTip(QtGui.QApplication.translate("MainWindow", "Topics", None, QtGui.QApplication.UnicodeUTF8))
        self.dockTopics.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Topics", None, QtGui.QApplication.UnicodeUTF8))
        self.dockIndex.setStatusTip(QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.dockIndex.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.dockSearch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.dockSearch.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.dockBookmark.setStatusTip(QtGui.QApplication.translate("MainWindow", "Bookmark", None, QtGui.QApplication.UnicodeUTF8))
        self.dockBookmark.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Bookmark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPage.setText(QtGui.QApplication.translate("MainWindow", "&Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPage.setIconText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPage.setToolTip(QtGui.QApplication.translate("MainWindow", "Print current page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPage.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Prints currently opened page.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPage.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_SettingsAction.setText(QtGui.QApplication.translate("MainWindow", "&Application settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_SettingsAction.setToolTip(QtGui.QApplication.translate("MainWindow", "Change the application settings", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_SettingsAction.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Change the application settings", None, QtGui.QApplication.UnicodeUTF8))
        self.bookmark_AddAction.setText(QtGui.QApplication.translate("MainWindow", "&Add bookmark", None, QtGui.QApplication.UnicodeUTF8))
        self.bookmark_AddAction.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds a bookmark for currently opened page", None, QtGui.QApplication.UnicodeUTF8))
        self.bookmark_AddAction.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Adds a bookmark for currently opened page. Remembers the opened page, and scroll position. Bookmarks are accessible through Bookmarks menu or tab.", None, QtGui.QApplication.UnicodeUTF8))
        self.bookmark_AddAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom &in", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setToolTip(QtGui.QApplication.translate("MainWindow", "Increase the font size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Increases the document font size.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setShortcut(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom &out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setToolTip(QtGui.QApplication.translate("MainWindow", "Decrease the font size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Decreases the document font size.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setShortcut(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOff.setText(QtGui.QApplication.translate("MainWindow", "Zoom &off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOff.setToolTip(QtGui.QApplication.translate("MainWindow", "restore normal font size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOff.setWhatsThis(QtGui.QApplication.translate("MainWindow", "set the document font size normal.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOff.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewHtmlSource.setText(QtGui.QApplication.translate("MainWindow", "&HTML Source", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewHtmlSource.setIconText(QtGui.QApplication.translate("MainWindow", "HTML source", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewHtmlSource.setToolTip(QtGui.QApplication.translate("MainWindow", "View HTML source of current page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewHtmlSource.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Shows the HTML source of currently opened page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewHtmlSource.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.view_Toggle_fullscreen_action.setText(QtGui.QApplication.translate("MainWindow", "Enable &full screen mode", None, QtGui.QApplication.UnicodeUTF8))
        self.view_Toggle_fullscreen_action.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Enters or leaves the fullscreen mode", None, QtGui.QApplication.UnicodeUTF8))
        self.view_Toggle_fullscreen_action.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.view_Toggle_contents_action.setText(QtGui.QApplication.translate("MainWindow", "Enable &side window", None, QtGui.QApplication.UnicodeUTF8))
        self.view_Toggle_contents_action.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Shows or hides the size window (with Content, Index, Search and Bookmark tabs)", None, QtGui.QApplication.UnicodeUTF8))
        self.view_Toggle_contents_action.setShortcut(QtGui.QApplication.translate("MainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocate.setText(QtGui.QApplication.translate("MainWindow", "&Locate ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocate.setToolTip(QtGui.QApplication.translate("MainWindow", "Locate the current page in side panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocate.setWhatsThis(QtGui.QApplication.translate("MainWindow", "If the current page is present in the Table of Contents, locate it there. ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocate.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChangeEncoding.setText(QtGui.QApplication.translate("MainWindow", "&Encoding", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChangeEncoding.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Changes the current document encoding. ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a CHM file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Opens a new CHM file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionBack.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionBack.setToolTip(QtGui.QApplication.translate("MainWindow", "Navigate back", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionBack.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Navigate back in navigation history", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionForward.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionForward.setToolTip(QtGui.QApplication.translate("MainWindow", "Navigate forward", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionForward.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Navigate forward in navigation history", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionHome.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionHome.setToolTip(QtGui.QApplication.translate("MainWindow", "Navigate home", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_actionHome.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Navigate to the document Home page, as specified in the document.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractFile.setText(QtGui.QApplication.translate("MainWindow", "&Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractFile.setIconText(QtGui.QApplication.translate("MainWindow", "Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Extract current CHM file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractFile.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Extract current CHM ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractFile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitApp.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitApp.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleSidebar.setText(QtGui.QApplication.translate("MainWindow", "Toggle Sidebar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setText(QtGui.QApplication.translate("MainWindow", "&Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("MainWindow", "&Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setText(QtGui.QApplication.translate("MainWindow", "Find &Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindPrevious.setText(QtGui.QApplication.translate("MainWindow", "Find &Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F3", None, QtGui.QApplication.UnicodeUTF8))

from pychmtabs import PyChmTabs
import images_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

